### PR TITLE
Create Que_19_#32

### PR DESCRIPTION
**Pull request by ManasiGDeshmukh**
Solution for Question 19 #32 in java lang @komalvhanmane

### CODE REVIEW

**Comment by ManasiGDeshmukh** [comment]
@komalvhanmane Sent to final solution

**Comment by komalvhanmane** [comment]
@ManasiGDeshmukh Code is not working properly its going in infinite loop..(runtime error) check and then update :)

**Comment by ManasiGDeshmukh** [comment]
@komalvhanmane It is running properly on my laptop....
please see if I need to make any changes in input style....
attaching a screenshot
image

**Comment by komalvhanmane** [comment]
@ManasiGDeshmukh Once try pasteing this input directly instead of giving one by one.

3
2
iioo
oooi
iiii
oooi
1
io
oo
2
oioi
ioio
oioi
ioio
Because there is problem while taking input. in online editor the code output is Runtime error So try to see what exactly happening while taking input.

**Comment by ManasiGDeshmukh** [comment]
@komalvhanmane updated.... can now copy paste input

**Comment by komalvhanmane** [comment]
@ManasiGDeshmukh only sample test cases are getting passed . Try to cover some edge cases . Internal test cases are not getting passed.

**Pull request closed without merging**
