### PR TITLE
Question 66

### PR DESCRIPTION
**Pull request by zsiecr**

### CODE REVIEW

**Comment by komalvhanmane** [comment]
@zsiecr This Question is assigned to other person . Your PR will not be accepted. Only make PR for the issues which are assigned to you !

**Comment by zsiecr** [comment]
okay, but at the time I made this pr there wasn't any assignee.
No problem, could you please assign me to one of the tasks?
I have also requested one.

**Comment by zsiecr** [comment]
I'm sorry if I was rude earlier. But can you assign this issue to me as well?

**Comment by komalvhanmane** [comment]
@zsiecr You can find issue's which is not assigned to anyone and comment there . :) we wont assign single issue to many people.

**Pull request closed without merging**
