### PR TITLE
Question 21 added

### PR DESCRIPTION
**Pull request by KanikaRaheja**
#36 Question 21 added.

### CODE REVIEW

**Comment by komalvhanmane** [comment]
@KanikaRaheja Its not allowed to make PR without getting assignment of issue.

**Comment by KanikaRaheja** [comment]
Please merge this PR as I am assigned now.

**Comment by komalvhanmane** [comment]
@KanikaRaheja Please add main method where user takes appropriate input. Its easy for me to check the working of your code.

**Comment by KanikaRaheja** [comment]
@komalvhanmane please check now.

**Pull request merged**
