### PR TITLE
Create Question202.cpp

### PR DESCRIPTION
**Pull request by surbhisawan**
Please merge my PR under Hactoberfest'22.

### CODE REVIEW

**Comment by komalvhanmane** [comment]
@surbhisawan for which issue you have made PR ? number ?

**Comment by surbhisawan** [comment]
issue #102

**Comment by komalvhanmane** [comment]
@surbhisawan Mention the Question number.

**Comment by komalvhanmane** [comment]
@surbhisawan There is no such question 202 !

**Pull request closed without merging**
