### PR TITLE
Create Que_19_#32

### PR DESCRIPTION
**Pull request by ManasiGDeshmukh**
Updated solution for que 19

@komalvhanmane

### CODE REVIEW

**Comment by ManasiGDeshmukh** [comment]
#32

**Comment by komalvhanmane** [comment]
@ManasiGDeshmukh Its still not working . and update in the same PR , don not make multiple PR's for the same issue .

**Comment by komalvhanmane** [comment]
@ManasiGDeshmukh Any update ?

**Comment by ManasiGDeshmukh** [comment]
@komalvhanmane can you please send which cases are not passing??

**Pull request closed without merging**
